services:
  flask_db:
    container_name: flask_db
    image: postgres:17
    env_file: 
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  flask_api:
    container_name: flask_api
    build:
      context: ./backend 
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - flask_db
    env_file:
      - ./backend/.env

volumes:
  postgres_data: